### ISSUE TITLE
Installation Instructions Clarity

### ISSUE THREAD

**Issue by BGaudreault-EDR** [jnbt/vscode-rufo#3]
Hello, I'm unable to follow the first step in your Installation instructions, which says "Press F1, type ext install then search for vscode-rufo", as "vscode-rufo" doesn't exist!  However there is a "rufo-vscode".

I was able to install Ruby and the gem rufo later, but I'm not sure how to activate Ruby formatting.  Normally I would open a document and press Alt+Shift+F, which Ctrl+Shift+P gets you to when searching for "Format Document", but I'm still getting a Microsoft Code error that "There is no formatter for 'ruby'-files installed.  What am I missing?

Also, how do we get to the "Settings" to apply them?

**Comment by jnbt** [comment]
@BGaudreault-EDR Thanks for your feedback.

You're right, something must have changed in the extension market place of VS Code. Now you need to search for `jnbt.vscode-rufo` in order to find my add-on.
Then you can open the settings menu of VS Code, select "Extensions" and scroll down to "Rufo".
There you can adjust the path to the Rufo executable.

I also updated the README to reflect this information.
